create table led_connections (
    id int AUTO_INCREMENT UNIQUE NOT NULL PRIMARY KEY,
	led_name VARCHAR(300) NOT NULL,
	sn VARCHAR(50) NOT NULL,
	ip VARCHAR(50) NOT NULL DEFAULT 'NULL',
	lok_id VARCHAR(10) NOT NULL,
	sim VARCHAR(12) NOT NULL DEFAULT 'NULL',
	last_chk INT DEFAULT 0 NOT NULL,
	disc_cntr BIGINT DEFAULT 0 NOT NULL,
	last_disc TIMESTAMP,
	UNIQUE(sn)
);